[package]
name = "redis-async"
version = "0.0.7"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "An asynchronous futures based Redis client for Rust using Tokio"
repository = "https://github.com/benashford/redis-async-rs"
keywords = ["redis", "tokio"]

[features]
default = []
commands = []

[dependencies]
bytes = "0.4.5"
futures = "0.1.16"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
